export const LINKED_IN_URL = 'https://www.linkedin.com/in/gabriele-ferrari-a5095b52/';
export const DATE_OF_BIRTH = new Date(1984, 11, 6);
export const SKILLS = {
  Assembly: 'just for fun',
  AWS: 'I\'ve used for Justmetrics in 2016',
  C: 'Yep, used for 10 yrs until 2012',
  'C++': 'Yep, used for 10 yrs until 2012',
  CSS: 'Yep, 10 yrs, still using it bro!',
  CENC: 'Yep, for few projects until 2017',
  'C#': 'Yep, used for 3 yrs until 2012',
  'D3.js': 'Yep, used for Justmetrics in 2016',
  Docker: 'Yep, for 3 yrs to now',
  'Ext.js': 'Yep, used for 5 yrs until 2019',
  Kotlin: 'Yep, used for 3 yrs until 2022',
  Kubernetes: 'Yep, for 3 yrs to now',
  GCP: 'Yep, for 3 yrs to now',
  HLS: 'Yep, used for few projects until 2017',
  HTML: 'Yep, 10yrs, and I am right now!',
  Java: 'Yep, until 2017',
  JavaScript: 'Yep, it\'s this output',
  JQuery: 'Yep, until 2018',
  Handlebars: 'Yep, until 2019 and sometimes come back (thanks Twilio!)',
  MongoDb: 'Yep, since 3.4, loving it!',
  MP4: 'Yep, I wrote a javascript repacker in 2018!',
  'MPEG-DASH': 'Yep, I wrote a javascript repacker in 2018!',
  'Next.js': 'Yep, for 3 yrs, this site is built with it',
  'Node.js': 'Yep, since 0.10 and onwards',
  OpenGL: 'Yep, back when I made videogames until 2012',
  Python: 'Just a few lines in 2012',
  PostgreSQL: 'Yep, for 3 yrs until 2022',
  React: 'Yep, for 3 yrs, to now!',
  Silverlight: 'RIP :)',
  'Shaka player': 'Yep, customized in 2018!',
  SmoothStreaming: 'Yep, for few years until 2018',
  SQL: 'Yep, 10 yrs to infinity',
  SQLServer: 'Yep, back in the days until 2012',
  TypeScript: 'Yep, since its birth to now',
  Widevine: 'Yep, got a certification in 2014',
};
