export const LINKED_IN_URL = 'https://www.linkedin.com/in/gabriele-ferrari-a5095b52/';
export const DATE_OF_BIRTH = new Date(1984, 11, 6);
export const SKILLS = {
  Agile: 'Yep, since 2009',
  Assembly: 'Yep, just for fun back in 2008',
  AWS: 'Yep, used for JustMetrics in 2016 - 2018',
  C: 'Yep, used for 10 yrs until 2012',
  'C++': 'Yep, used for 10 yrs until 2012',
  'C#': 'Yep, used for 3 yrs until 2012',
  CENC: 'Yep, for few projects until 2017',
  'CI/CD': 'Yep, since 2012',
  CSS: 'Yep, since 2008, still using it here bro!',
  'D3.js': 'Yep, used for JustMetrics in 2016 - 2018',
  DevOps: 'Yep, since 2019! ps: the methodology!',
  Docker: 'Yep, since 2019, loving it!',
  'Ext.js': 'Yep, used for 5 yrs until 2019',
  GCP: 'Yep, since 2019, loving it!',
  Handlebars: 'Yep, until 2019 but sometimes it reappears (thanks Sendgrid!)',
  HLS: 'Yep, used for few projects until 2017',
  HTML: 'Yep, since 2008, it\'s what you\'re reading!',
  Java: 'Yep, until 2017',
  JavaScript: 'Yep, it\'s this output',
  JQuery: 'Yep, until 2018',
  Kotlin: 'Yep, used for 3 yrs until 2022',
  Kubernetes: 'Yep, since 2019, loving it!',
  Kanban: 'Yep, since 2013',
  MongoDb: 'Yep, since 2016, loving it!',
  'MPEG-4': 'Yep, I wrote a JavaScript remuxer in 2018!',
  'MPEG-DASH': 'Yep, I wrote a JavaScript remuxer in 2018!',
  'Next.js': 'Yep, since 2019, this thing is built with it!',
  'Node.js': 'Yep, since 2014, it\'s my fav',
  OpenGL: 'Yep, back when I made videogames until 2012',
  Python: 'Just a few lines in 2012',
  PostgreSQL: 'Yep, since 2019',
  'React.js': 'Yep, since 2019, you\'re seeing it in action!',
  SCRUM: 'Yep, since 2009 to 2013, then Kanban :)',
  Silverlight: 'RIP :)',
  'Shaka player': 'Yep, forked and customized in 2018!',
  SmoothStreaming: 'Yep, for few years until 2018',
  SQL: 'Yep, since 2015',
  SQLServer: 'Yep, back in the days until 2012',
  TDD: 'Yep, since 2016',
  TypeScript: 'Yep, since 2017, fav language ATM',
  VBScript: 'Lol, this was the first language I learned in 2001. Hopefully you won\'t need it!',
  Widevine: 'Yep, got a certification in 2014',
};
